# Generated by Django 3.0.7 on 2020-06-23 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('user_type', models.CharField(blank=True, choices=[('MG', 'Менеджер'), ('CW', 'Сотрудник')], default='CW', max_length=10, null=True)),
                ('user_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128, null=True, verbose_name='Название вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('question_type', models.CharField(blank=True, choices=[('RADIO', 'c одним вариантом ответа'), ('CHECKBOXES', ' с несколькими вариантами')], default='RADIO', max_length=10, verbose_name='тип вопросов')),
                ('answer_right', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='Название опросника')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('date_start', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата начала опроса')),
                ('date_finish', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата окончания опроса')),
                ('answer_weight', models.SmallIntegerField(default=1, verbose_name='Баллы за ответ')),
                ('questions', models.ManyToManyField(to='liz.Question')),
                ('users', models.ManyToManyField(blank=True, to='liz.Employee', verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответ на вопрос')),
                ('is_correct', models.BooleanField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.Questionnaire', verbose_name='вопросы')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.Employee', verbose_name='сотрудники')),
            ],
            options={
                'verbose_name': 'ответ сотрудника',
                'verbose_name_plural': 'ответы сотрудников',
            },
        ),
    ]
