# Generated by Django 3.0.7 on 2020-06-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeanswer',
            name='questionnaries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liz.Questionnaire', verbose_name='вопросник'),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.Question', verbose_name='вопросы'),
        ),
    ]
