# Generated by Django 3.0.7 on 2020-06-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('MG', 'Manager'), ('CW', 'Coworker')], default='CW', max_length=10),
        ),
    ]
