# Generated by Django 3.0.7 on 2020-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0002_auto_20200623_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeanswer',
            options={'verbose_name': 'ответы сотрудника', 'verbose_name_plural': 'ответы сотрудников'},
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='answer_weight',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_weight',
            field=models.SmallIntegerField(default=1, verbose_name='Баллы за ответ'),
        ),
    ]
