# Generated by Django 3.0.7 on 2020-06-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0004_auto_20200612_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
