# Generated by Django 3.0.7 on 2020-06-23 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0004_auto_20200623_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата начала опроса')),
                ('date_finish', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата окончания опроса')),
            ],
            options={
                'verbose_name': '4) Опросники открытые',
                'verbose_name_plural': '4) Опросники открытые',
            },
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='date_start',
        ),
        migrations.DeleteModel(
            name='ApointmentTo',
        ),
        migrations.AddField(
            model_name='appointto',
            name='questionnaires',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='liz.Questionnaire', verbose_name='опросник'),
        ),
        migrations.AddField(
            model_name='appointto',
            name='users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='liz.Employee', verbose_name='сотрудник'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='users',
            field=models.ManyToManyField(blank=True, through='liz.AppointTo', to='liz.Employee', verbose_name='Открыто для отрудников'),
        ),
    ]
