# Generated by Django 3.0.7 on 2020-06-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0005_auto_20200623_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointto',
            options={'verbose_name': 'Опросники открытые', 'verbose_name_plural': 'Опросники открытые'},
        ),
        migrations.AlterModelOptions(
            name='employeeanswer',
            options={'verbose_name': '4) Ответы сотрудника', 'verbose_name_plural': '4) Ответы сотрудников'},
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liz.Employee', verbose_name='сотрудники'),
        ),
    ]
