# Generated by Django 3.0.7 on 2020-06-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0006_auto_20200616_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(blank=True, choices=[('RADIO', 'choose_several'), ('CHECKBOXES', 'choose_one')], max_length=10, verbose_name='тип вопросов')),
                ('qr_title', models.CharField(max_length=25)),
                ('qr_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RightAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.Question')),
                ('questionnarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.QuestionnaireType')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_question', to='liz.QuestionnaireContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='liz.Employee')),
                ('user_answer', models.ManyToManyField(to='liz.QuestionnaireContent')),
            ],
        ),
    ]
