# Generated by Django 3.0.7 on 2020-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0006_auto_20200624_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointto',
            options={'verbose_name': ' Опросник у сотрудника ', 'verbose_name_plural': '4) Раздать опросники'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': '1) Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeanswer',
            options={'verbose_name': 'Ответы сотрудника', 'verbose_name_plural': '5) Посмотреть ответы сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': '2) Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Опросник', 'verbose_name_plural': '3) Опросники'},
        ),
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='questionnaries',
            new_name='questionnaires',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_right',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
