# Generated by Django 3.0.7 on 2020-06-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0007_auto_20200625_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_all_variants',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='варианты ответов (среди них должен быть и правильный)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_weight',
            field=models.SmallIntegerField(default=1, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=128, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(related_name='questionnaires', to='liz.Question', verbose_name='Вопросы в текущем опроснике'),
        ),
    ]
