# Generated by Django 3.0.7 on 2020-06-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0007_employeeanswer_questionnairecontent_questionnairetype_rightanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник'},
        ),
        migrations.AlterModelOptions(
            name='employeeanswer',
            options={'verbose_name': 'ответ сотрудника', 'verbose_name_plural': 'ответы сотрудника'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionnairecontent',
            options={'verbose_name': 'Содержание опросника', 'verbose_name_plural': 'Содержание опросников'},
        ),
        migrations.AlterModelOptions(
            name='rightanswer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveField(
            model_name='questionnairecontent',
            name='point',
        ),
        migrations.RemoveField(
            model_name='questionnairecontent',
            name='questionnarie',
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('RADIO', 'c одним вариантом ответа'), ('CHECKBOXES', ' с несколькими вариантами')], max_length=10, verbose_name='тип вопросов'),
        ),
        migrations.AddField(
            model_name='questionnairecontent',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='questionnairecontent',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Название опросника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(blank=True, choices=[('MG', 'Manager'), ('CW', 'Coworker')], default='CW', max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='employeeanswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name='questionnairecontent',
            name='question',
        ),
        migrations.AddField(
            model_name='questionnairecontent',
            name='question',
            field=models.ManyToManyField(to='liz.Question'),
        ),
        migrations.DeleteModel(
            name='QuestionnaireType',
        ),
    ]
