# Generated by Django 3.0.7 on 2020-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0008_auto_20200629_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='right_variant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='variant_1',
            field=models.CharField(max_length=128, null=True, verbose_name='1 вариант ответа в опроснике'),
        ),
        migrations.AddField(
            model_name='question',
            name='variant_2',
            field=models.CharField(max_length=128, null=True, verbose_name='2 вариант ответа в опроснике'),
        ),
        migrations.AddField(
            model_name='question',
            name='variant_3',
            field=models.CharField(max_length=128, null=True, verbose_name='3 вариант ответа в опроснике'),
        ),
        migrations.AddField(
            model_name='question',
            name='variant_4',
            field=models.CharField(max_length=128, null=True, verbose_name='4 вариант ответа в опроснике'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_all_variants',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='варианты ответов (в том числе все правильные)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_right',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='правильные ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_weight',
            field=models.SmallIntegerField(default=0, verbose_name='баллы'),
        ),
    ]
