# Generated by Django 3.0.7 on 2020-06-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0009_auto_20200629_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='right_variant',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='variant_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('One', 'Один правильный ответ'), ('Multi', 'Несколько правильных ответов')], default='One', max_length=10, verbose_name='тип вопросов'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=128, null=True, verbose_name='варианты ответа в опроснике')),
                ('is_right_variant', models.BooleanField(verbose_name='укажите правильные варианты')),
                ('answer_weight', models.SmallIntegerField(default=0, verbose_name='баллы')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liz.Question', verbose_name='вопросы')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
