# Generated by Django 3.0.7 on 2020-08-14 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liz', '0011_auto_20200814_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questionnaires',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_in_questionnaire', to='liz.Questionnaire', verbose_name='опросник'),
        ),
    ]
